# Generated by Django 6.0.2 on 2026-02-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=512, null=True)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100, null=True)),
                ('sha256_hash', models.CharField(db_index=True, max_length=64, null=True)),
                ('download_path', models.CharField(max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
